// <auto-generated />
using System;
using System.Collections.Generic;
using Lime.Data;
using Lime.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lime.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260426030024_AddPointsAndRevisions")]
    partial class AddPointsAndRevisions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lime.Api.Models.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<List<ArtistRef>>("Artists")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("artists");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("text")
                        .HasColumnName("cover_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name");

                    b.Property<string>("ReleaseDate")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("release_date");

                    b.Property<string>("SpotifyId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("spotify_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("SpotifyId")
                        .IsUnique()
                        .HasDatabaseName("ix_albums_spotify_id");

                    b.ToTable("albums", (string)null);
                });

            modelBuilder.Entity("Lime.Api.Models.Follow", b =>
                {
                    b.Property<Guid>("FollowerId")
                        .HasColumnType("uuid")
                        .HasColumnName("follower_id");

                    b.Property<Guid>("FolloweeId")
                        .HasColumnType("uuid")
                        .HasColumnName("followee_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("FollowerId", "FolloweeId");

                    b.HasIndex("FolloweeId")
                        .HasDatabaseName("ix_follows_followee_id");

                    b.ToTable("follows", null, t =>
                        {
                            t.HasCheckConstraint("ck_follows_no_self", "follower_id <> followee_id");
                        });
                });

            modelBuilder.Entity("Lime.Api.Models.PointTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Delta")
                        .HasColumnType("integer")
                        .HasColumnName("delta");

                    b.Property<short>("Reason")
                        .HasColumnType("smallint")
                        .HasColumnName("reason");

                    b.Property<Guid?>("RefId")
                        .HasColumnType("uuid")
                        .HasColumnName("ref_id");

                    b.Property<string>("RefType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("ref_type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_point_transactions_user_created");

                    b.ToTable("point_transactions", (string)null);
                });

            modelBuilder.Entity("Lime.Api.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("ReplacedById")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_id");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_refresh_tokens_expires_at");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Lime.Api.Models.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AlbumId")
                        .HasColumnType("uuid")
                        .HasColumnName("album_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("edited_at");

                    b.Property<decimal>("Rating")
                        .HasColumnType("numeric(3,1)")
                        .HasColumnName("rating");

                    b.Property<Guid?>("TrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("track_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId")
                        .HasDatabaseName("ix_reviews_album_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_reviews_created_at");

                    b.HasIndex("TrackId")
                        .HasDatabaseName("ix_reviews_track_id");

                    b.HasIndex("UserId", "AlbumId")
                        .IsUnique()
                        .HasDatabaseName("ux_reviews_user_album_alive")
                        .HasFilter("album_id IS NOT NULL AND deleted_at IS NULL");

                    b.HasIndex("UserId", "TrackId")
                        .IsUnique()
                        .HasDatabaseName("ux_reviews_user_track_alive")
                        .HasFilter("track_id IS NOT NULL AND deleted_at IS NULL");

                    b.ToTable("reviews", null, t =>
                        {
                            t.HasCheckConstraint("ck_reviews_exactly_one_target", "(track_id IS NOT NULL)::int + (album_id IS NOT NULL)::int = 1");
                        });
                });

            modelBuilder.Entity("Lime.Api.Models.ReviewReaction", b =>
                {
                    b.Property<Guid>("ReviewId")
                        .HasColumnType("uuid")
                        .HasColumnName("review_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<short>("Kind")
                        .HasColumnType("smallint")
                        .HasColumnName("kind");

                    b.HasKey("ReviewId", "UserId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_review_reactions_user_id");

                    b.ToTable("review_reactions", (string)null);
                });

            modelBuilder.Entity("Lime.Api.Models.ReviewRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("Rating")
                        .HasColumnType("numeric(3,1)")
                        .HasColumnName("rating");

                    b.Property<Guid>("ReviewId")
                        .HasColumnType("uuid")
                        .HasColumnName("review_id");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId", "CreatedAt")
                        .HasDatabaseName("ix_review_revisions_review_created");

                    b.ToTable("review_revisions", (string)null);
                });

            modelBuilder.Entity("Lime.Api.Models.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AlbumId")
                        .HasColumnType("uuid")
                        .HasColumnName("album_id");

                    b.Property<List<ArtistRef>>("Artists")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("artists");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name");

                    b.Property<string>("PreviewUrl")
                        .HasColumnType("text")
                        .HasColumnName("preview_url");

                    b.Property<string>("SpotifyId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("spotify_id");

                    b.Property<int?>("TrackNumber")
                        .HasColumnType("integer")
                        .HasColumnName("track_number");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId")
                        .HasDatabaseName("ix_tracks_album_id");

                    b.HasIndex("SpotifyId")
                        .IsUnique()
                        .HasDatabaseName("ix_tracks_spotify_id");

                    b.ToTable("tracks", (string)null);
                });

            modelBuilder.Entity("Lime.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<int>("NicknameChanges")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("nickname_changes");

                    b.Property<int>("Points")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("points");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Lime.Api.Models.UserOAuthAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTime>("LinkedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("linked_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("provider_user_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_oauth_accounts_user_id");

                    b.HasIndex("Provider", "ProviderUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_oauth_accounts_provider_provider_user_id");

                    b.ToTable("user_oauth_accounts", (string)null);
                });

            modelBuilder.Entity("Lime.Api.Models.UserSpotifyLink", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime?>("AccessExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("access_expires_at");

                    b.Property<string>("AccessToken")
                        .HasColumnType("text")
                        .HasColumnName("access_token");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<string>("Scope")
                        .HasColumnType("text")
                        .HasColumnName("scope");

                    b.Property<string>("SpotifyUserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("spotify_user_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId");

                    b.ToTable("user_spotify_links", (string)null);
                });

            modelBuilder.Entity("Lime.Api.Models.Follow", b =>
                {
                    b.HasOne("Lime.Api.Models.User", "Followee")
                        .WithMany()
                        .HasForeignKey("FolloweeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_follows_users_followee_id");

                    b.HasOne("Lime.Api.Models.User", "Follower")
                        .WithMany()
                        .HasForeignKey("FollowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_follows_users_follower_id");

                    b.Navigation("Followee");

                    b.Navigation("Follower");
                });

            modelBuilder.Entity("Lime.Api.Models.PointTransaction", b =>
                {
                    b.HasOne("Lime.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_point_transactions_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lime.Api.Models.RefreshToken", b =>
                {
                    b.HasOne("Lime.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lime.Api.Models.Review", b =>
                {
                    b.HasOne("Lime.Api.Models.Album", "Album")
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_reviews_albums_album_id");

                    b.HasOne("Lime.Api.Models.Track", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_reviews_tracks_track_id");

                    b.HasOne("Lime.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_users_user_id");

                    b.Navigation("Album");

                    b.Navigation("Track");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lime.Api.Models.ReviewReaction", b =>
                {
                    b.HasOne("Lime.Api.Models.Review", "Review")
                        .WithMany("Reactions")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_review_reactions_reviews_review_id");

                    b.HasOne("Lime.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_review_reactions_users_user_id");

                    b.Navigation("Review");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lime.Api.Models.ReviewRevision", b =>
                {
                    b.HasOne("Lime.Api.Models.Review", "Review")
                        .WithMany()
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_review_revisions_reviews_review_id");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("Lime.Api.Models.Track", b =>
                {
                    b.HasOne("Lime.Api.Models.Album", "Album")
                        .WithMany("Tracks")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_tracks_albums_album_id");

                    b.Navigation("Album");
                });

            modelBuilder.Entity("Lime.Api.Models.UserOAuthAccount", b =>
                {
                    b.HasOne("Lime.Api.Models.User", "User")
                        .WithMany("OAuthAccounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_oauth_accounts_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lime.Api.Models.UserSpotifyLink", b =>
                {
                    b.HasOne("Lime.Api.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("Lime.Api.Models.UserSpotifyLink", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_spotify_links_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lime.Api.Models.Album", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("Lime.Api.Models.Review", b =>
                {
                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("Lime.Api.Models.User", b =>
                {
                    b.Navigation("OAuthAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
